### PR TITLE
Add STIMESTAMP_MS

### PR DESCRIPTION
**Pull request by youssef-lr**
### Fixed Issues
- https://github.com/Expensify/Auth/pull/11913#discussion_r1710388405

### Tests

_________
**Internal Testing Reminder:** when changing bedrock, please compile auth against your new changes

### CODE REVIEW

**Review by cead22 — APPROVED** [review]

**Comment by cead22** [comment]
@youssef-lr can you link the issue this is related to?

**Comment by youssef-lr** [comment]
it's this comment from Tyler https://github.com/Expensify/Auth/pull/11913#discussion_r1710388405

**Comment by cead22** [comment]
Any tests we can add here or in the PR that will use this?

**Comment by youssef-lr** [comment]
We have existing tests in Auth that covers this. If they pass we should be good to go. I'll run them locally and report back here

**Comment by youssef-lr** [comment]
@cead22 

Screenshot 2024-08-12 at 21 26 44
Screenshot 2024-08-12 at 21 26 29

**Pull request merged**
