### PR TITLE
Skip munmap call

### PR DESCRIPTION
**Pull request by tylerkaraszewski**
### Details
This is a similar experiment as we did here: https://github.com/Expensify/Bedrock/pull/928

Except this time we're going to skip munmap entirely and see how that goes.

@righdforsa - when you try this, please record the results in the comments on this PR or the issue.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/171333

### Tests
We'll do it live.

### CODE REVIEW

**Comment by righdforsa** [comment]
> @righdforsa - when you try this, please record the results in the comments on this PR or the issue.

👍

**Review by righdforsa — APPROVED** [review]
👍  LGTM. We will test this on one node, time a few shutdowns with it running, and decide whether to roll out to the rest of the pool.

**Comment by coleaeason** [comment]
what do we expect this to do? i don't see anything in the linked issue about this. Anyone have context to provide in either place? This looks like it will do exactly nothing to save any time to me.

**Comment by righdforsa** [comment]
@coleaeason context is here: https://expensify.slack.com/archives/C094TGUTZ/p1626976743345100?thread_ts=1626103945.155300&cid=C094TGUTZ
> tyler  3 hours ago
Here's an experiment we could try:
Same as the above one to log timing for munmap, but don't call munmap, just skip the call entirely and see if if ends up faster.

> tyler  3 hours ago
I can make that pretty fast if someone wants to try it.

> chris  3 hours ago
Oh, YEAH, let’s just skip the munmap

> chris  3 hours ago
is there some unknown danger of that? AFAIK, once the process dies the kernel will release that memory (but that’s based on assumption rather than knowledge)

> chris  3 hours ago
I can make that pretty fast if someone wants to try it.
yes please, @tyler, I will shepherd that test (edited) 

> chris  3 hours ago
it’s going to be INSANE

> tyler  3 hours ago
   munmap()
       The munmap() system call deletes the mappings for the specified address range,  and  causes
       further  references  to  addresses  within the range to generate invalid memory references.
       The region is also automatically unmapped when the process is  terminated.   On  the  other
       hand, closing the file descriptor does not unmap the region.

> chris  3 hours ago
I love it :heart_eyes:

> tyler  3 hours ago
Exactly what "when the process is terminated" means is unclear, it does not specify "as it is terminating, before it is done" versus "by the kernel, after the process exits".

**Pull request merged**
