### PR TITLE
Add setVersion status command

### PR DESCRIPTION
**Pull request by coleaeason**
@tylerkaraszewski Please review. Setting the versionOverride in the init script we run the servers with is fine for when we want to keep the versionOverride set between restarts, etc. but sometimes like when we're testing sqlite versions, we just want the version changed temporarily and then when we restart the node we want the node to come back up with it's actual version. Setting in the init script makes it _really_ easy for us to forget we did that (see recent deploy issues), but if restarting the node cleared the override, we wouldn't have to remember to change anything. This will also decrease the amount of times we need to bounce nodes, get keys, etc. and should be quite the time saver for us I think.

cc: @Expensify/infra @cead22 @flodnv 

## Tests
```
vagrant@vagrant-ubuntu-trusty-64:~$ nc localhost 4444
setversion

404 Must supply a version
nodeName: auth-on-bedrock
totalTime: 18
Content-Length: 0

setversion
version: XXXXX

200 OK
nodeName: auth-on-bedrock
totalTime: 44
Content-Length: 124

{"newVersion":"XXXXX","oldVersion":"16c2557a15c28de5753f7fb48d13f6b4d9e03ff7:Auth_1b76326e35e4a85d6e82da62bb66760368e78a61"}

status

200 OK
nodeName: auth-on-bedrock
totalTime: 92
Content-Length: 305

{"CommitCount":515,"escalatedCommandList":[],"host":"localhost:4445","isMaster":true,"multiWriteBlacklist":"","multiWriteWhiteList":[],"peerList":[],"plugins":[{"name":"Auth","version":"1b76326e35e4a85d6e82da62bb66760368e78a61"},{"name":"DB"}],"queuedCommandList":[],"state":"MASTERING","version":"XXXXX"}
```

Also tested the sorting by trying to set the new version to the opposite order:
```
vagrant@vagrant-ubuntu-trusty-64:~$ nc localhost 4444
status

200 OK
nodeName: auth-on-bedrock
totalTime: 118
Content-Length: 386

{"CommitCount":515,"escalatedCommandList":[],"host":"localhost:4445","isMaster":true,"multiWriteBlacklist":"","multiWriteWhiteList":[],"peerList":[],"plugins":[{"name":"Auth","version":"1b76326e35e4a85d6e82da62bb66760368e78a61"},{"name":"DB"}],"queuedCommandList":[],"state":"MASTERING","version":"057dc3f60c583981bde6cc11701d29382b53a6a5:Auth_1b76326e35e4a85d6e82da62bb66760368e78a61"}

setversion
version: Auth_1b76326e35e4a85d6e82da62bb66760368e78a61:057dc3f60c583981bde6cc11701d29382b53a6a5

200 OK
nodeName: auth-on-bedrock
totalTime: 51
Content-Length: 205

{"newVersion":"057dc3f60c583981bde6cc11701d29382b53a6a5:Auth_1b76326e35e4a85d6e82da62bb66760368e78a61","oldVersion":"057dc3f60c583981bde6cc11701d29382b53a6a5:Auth_1b76326e35e4a85d6e82da62bb66760368e78a61"}

status

200 OK
nodeName: auth-on-bedrock
totalTime: 96
Content-Length: 386

{"CommitCount":515,"escalatedCommandList":[],"host":"localhost:4445","isMaster":true,"multiWriteBlacklist":"","multiWriteWhiteList":[],"peerList":[],"plugins":[{"name":"Auth","version":"1b76326e35e4a85d6e82da62bb66760368e78a61"},{"name":"DB"}],"queuedCommandList":[],"state":"MASTERING","version":"057dc3f60c583981bde6cc11701d29382b53a6a5:Auth_1b76326e35e4a85d6e82da62bb66760368e78a61"}
```

### CODE REVIEW

**Comment by coleaeason** [comment]
Added a hold for https://github.com/Expensify/Bedrock/pull/262 since without it, this command would be impossible to send to any node but master since a slave's version on start up wouldn't match master and their port would close.

**Comment by tylerkaraszewski** [comment]
This won't work on master. The SQLiteNode is started up with a particular version, and it will keep broadcasting that version to slaves even if the `_version` property of `BedrockServer` changes later.

**Comment by coleaeason** [comment]
Discussed a bit with Tyler how we might be able to make this work after the control port change is merged. I'll work with him on that after it's merged.

**Comment by coleaeason** [comment]
@tylerkaraszewski care to review?

**Comment by tylerkaraszewski** [comment]
Let's do this another way with detached mode.

**Pull request closed without merging**
