### PR TITLE
Make bedrock GCC13 compatible

### PR DESCRIPTION
**Pull request by coleaeason**
@tylerkaraszewski Please review. This is the first step in moving us to gcc 13 for all of the plugin repos.

gcc 13 treats `range-loop-analysis` as an error when the loop doesn't return a copy and the construct is "expensive" to create, so the one code change here is 

```diff
- (const auto peer : _peerList)
+ (const auto& peer : _peerList)
```

The other changes in tpunit are needed to support Auth tests which were not compiling due to a new error for discarding the result of the `+` operator. 

Note: This change does not actually migrate the compiler, it only makes the code compatible. 

### Fixed Issues
Part of https://github.com/Expensify/Expensify/issues/334261

### Tests
Existing test pass, auth tests pass. 
_________
**Internal Testing Reminder:** when changing bedrock, please compile auth against your new changes

### CODE REVIEW

**Review by tylerkaraszewski — DISMISSED** [review]
Do we want to make the code changes first and the compiler changes separately? That was we can get all of the code updated in all of the repos and then try to do the compiler switchover everywhere at once. 

If the code changes are small enough though, like they are here, we can probably just do them all as one.

**Comment by coleaeason** [comment]
@tylerkaraszewski auth changes are same as here, just fixing loops that make copies. I'm happy to split these PRs if you want, let me know.

**Comment by tylerkaraszewski** [comment]
What's the deploy plan for this? Press "merge" on every repo at once and then immediately start an auth deploy?

I'm fine with that. I do think it's clearer to do a revert and rollback if we're only changing the makefile and travis files and such and not 9000 lines of library code and missing references.

So I think it'd be a good idea to split out the code changes to a separate PR that we can first, make sure that works, and then just change compilers separately.

**Comment by coleaeason** [comment]
Updated @tylerkaraszewski

**Review by tylerkaraszewski — APPROVED** [review]

**Pull request merged**
