### PR TITLE
Use std::thread instead of pthreads

### PR DESCRIPTION
**Pull request by Vadius**
Due to big code moves I advice to review the PR commit-by-commit.
All unittests works fine, `./bedrock -clean` also works w/o visible changes in logs.
Didn't test distributed deployment, but changes shouldn't affect it.

### CODE REVIEW

**Comment by quinthar** [comment]
Whoa, I'll let @tylerkaraszewski review this one.

**Comment by quinthar** [comment]
Impressive work, thanks!

**Comment by quinthar** [comment]
@Vadius Why was this closed?

@tylerkaraszewski - Do you want to merge this, or would you prefer to keep using pthreads?

**Comment by Vadius** [comment]
Oops.. obviously, confused with window, pardon.

**Comment by tylerkaraszewski** [comment]
I haven't reviewed this yet not because I don't think it's a good idea (I do), but because I have another branch in progress that does this as well, (see: https://github.com/Expensify/Bedrock/compare/tyler-multi-write?expand=1) alongside a bunch of other changes. That branch will probably get discarded, but I could pull the threading changes out of it and keep those, which include some things mentioned in this change but not implemented (i.e., using `condition_variable` instead of a sleep loop, replacing `SThreadSleep` with `sleep_for`, etc.

And I haven't had the time to compare the two branches, but don't want to merge this one if I'd rather use mine, because it will have a massive set of conflicts.

**Comment by Vadius** [comment]
@tylerkaraszewski , you have many changes similar to mine, so I think it's ok to discard this PR and use your one.

**Comment by Vadius** [comment]
@quinthar, I think this PR should be closed to avoid ancient code. Is it ok?

**Pull request closed without merging**
