### PR TITLE
Never send the response of a connection:forget command

### PR DESCRIPTION
**Pull request by iwiznia**
@tylerkaraszewski please review. /cc @flodnv 

Is this the correct fix? Especially the fact that I'm not doing `_socketIDMap.erase(socketIt);`, which not sure if is necessary or not. The thing is that we _might_ use the socket for another command or we might not. If we don't, then we could never free that socket, but if we do we need to keep the socket.... 🤔 
Locally it makes the tests pass, that used to fail in this PR https://github.com/Expensify/Web-Expensify/pull/19313

Needed to fix https://github.com/Expensify/Expensify/issues/66144

### CODE REVIEW

**Comment by tylerkaraszewski** [comment]
Sending `connection: forget` should close the socket. Reusing a connection after telling the server to forget it seems like a bug. This should be analogous to `connection: close` in standard HTTP. (Why don't we just use `connection: close` instead of `forget`?)

**Comment by iwiznia** [comment]
heh, so it all comes to: what's the difference between `connection: close` and `connection: forget`? My take was: `close` means close the socket right after responding because I won't be reusing it and `forget` means I don't need to know the response to this, just confirm you got it.
Are you proposing that if you pass `forget` it's implied that it needs to close it too? If so, why? In this case, we want to keep using the socket ideally.

**Comment by tylerkaraszewski** [comment]
Well, I think `connection: forget` is a bad name for a feature that is "Queue a command that will receive no response, but keep the connection open".

I think the correct solution is to not associate a socket with a `forget` command. Something like adding `s->id = 0` around [here](https://github.com/Expensify/Bedrock/blob/master/BedrockServer.cpp#L1207), though there's more to it than that. This makes the socket immediately available to send another command, as we'll never look up that socket when processing the response to the first command, and it can't conflict in the `_socketIDMap`.

You can see that we *do* send a response on `connection: forget` requests [here](https://github.com/Expensify/Bedrock/blob/master/BedrockServer.cpp#L1211). The client needs to read this response if we're going to continue sending it.

We still don't have a good mechanism for detecting if this connection will ever be used again, but if the client closes it, that should be handled correctly. We might also want timeouts on inactive sockets, as well.

I think maybe `response: none` makes more sense than `connection: forget` if we want to keep the connection but not respond to it.

**Comment by iwiznia** [comment]
ok, updated. Didn't change the name of `connection:forget`, we can do that separately.

**Comment by quinthar** [comment]
I'm not sure where this landed, but to confirm, the original intent for a `Connection: forget` request was that it *would* return a response -- enough to say "I successfully received and queued this message, and am ready to receive another one".  However, it would *not* send the final command response.  This means that it should be 100% fine to reuse a connection with a `Connection: forget` request -- and indeed, if you want to queue a shitload of commands super fast, this would be the recommended way to do it.  Does this make sense, and is this how it still works today?

**Comment by iwiznia** [comment]
Yes, that's how it should be working right now.

**Pull request merged**
