### PR TITLE
#937 - fix mysql plugin args processing

### PR DESCRIPTION
**Pull request by samsk**
Small fix to MySQL plugin, allowing it to process command line arguments.

### CODE REVIEW

**Comment by jveres** [comment]
I'm facing with this issue too, could this PR be merged?

**Comment by quinthar** [comment]
@tylerkaraszewski can you evaluate?

**Review by tylerkaraszewski — APPROVED** [review]

**Comment by tylerkaraszewski** [comment]
Happy to merge this change but we require commits to be signed in this repo. Would you mind signing the commits for this change @samsk?

**Comment by samsk** [comment]
I've signed it, hope its ok

**Review by tylerkaraszewski — APPROVED** [review]

**Comment by tylerkaraszewski** [comment]
Sorry, it looks like two of the three commits in the branch are signed, but not the first one.

**Review by tylerkaraszewski — APPROVED** [review]

**Comment by tylerkaraszewski** [comment]
Merged! Sorry that was such a process.

**Comment by samsk** [comment]
No problem, I'm happy I could help. Thank you.

**Pull request merged**
