### PR TITLE
Update SQLite to 3.43.0 (JSON optimizations)

### PR DESCRIPTION
**Pull request by aldo-expensify**
### Details

SQLite team added some optimizations that improve performance when handling big JSONs (for example, big policies)
This is in the context of optimizing the `SharePolicy` command.
More info: see email chain with subject "Reusing parsed JSON in indexes"

SO about updating SQLite version: https://stackoverflowteams.com/c/expensify/questions/154

How I produced the sqlite.c and sqlite.h:

1. Downloaded tar ball from https://sqlite.org/src/info/bedrock as pointed out by Richard
2. Configured with `./configure --enable-fts5 --enable-update-limit`
3. Compiled with `make sqlite3.c shell.c`

Configuration/compile instructions obtained from:  https://github.com/Expensify/Salt/blob/main/build/files/jenkins/build_scripts/build_sqlite3-cli.sh#L73-L77

# First we have to generate the sqlite3 amalgamation and header.

### Fixed Issues
Fixes https://github.com/Expensify/Expensify/issues/289995 (partially)

### Tests

Automated tests should run and not explode?
_________
**Internal Testing Reminder:** when changing bedrock, please compile auth against your new changes

### CODE REVIEW

**Comment by aldo-expensify** [comment]
cc @tylerkaraszewski since you usually do the sqlite updates

**Comment by coleaeason** [comment]
LGTM -- automated tests not exploding is basically the bar for merging

**Comment by aldo-expensify** [comment]
Making it ready for review then.

**Review by hayata-suenaga — APPROVED** [review]
>  automated tests not exploding is basically the bar for merging

I'm basing my review on this 🤣

**Review by flodnv — APPROVED** [review]

**Comment by hayata-suenaga** [comment]
oh no...

**Comment by aldo-expensify** [comment]
Ahhhhhhh crap I think I know what went wrong, I missed adding the file libstuff/sqlite3ext.h to the commit.
I'll prepare a new Bedrock PR with all the needed files and I'll rerun all tests locally to make sure it is not failing the same way.

**Comment by aldo-expensify** [comment]
hmm, forgetting `libstuff/sqlite3ext.h` doesn't seem to be the problem. The tests fail anyway 🤔

**Pull request merged**
