### PR TITLE
[WIP] Re-hashing passwords

### PR DESCRIPTION
**Pull request by joelbettner**
@mattabullock 

To be done in conjunction with https://github.com/Expensify/Server-Expensify/pull/2457

Files changed that were not from addition of libsodium library:
`Makefile`
`libstuff/libstuff.cpp`

### CODE REVIEW

**Comment by quinthar** [comment]
Out of curiosity, why use a new library for hashing, rather than using one of the algorithms already present in mbedtls?   https://tls.mbed.org/api/group__hashing__module.html is argon2 so much better than salted sha256 as to warrant the extra library?

**Comment by quinthar** [comment]
Basically, we're adding 544 separate files, just to add a single function.  I realize that they're "just files", but I mean, that just seems sorta silly.  If we're uncomfortable with the speed of SHA-256, what about SHA-512?  Or running SHA-512 1000 times in a row?

**Comment by tylerkaraszewski** [comment]
Hey @joelbettner I talked to @quinthar about this and we think there's a better way to do this.

Firstly, since this is a change for auth, let's do it in the auth repo. This will keep the open source project from needing to ingest this library just to support an Expensify-specific function.

Second, we don't need to build this library ourselves, we can just use the pre-packaged one. You can install this in your VM by doing `sudo apt-get install libsodium-dev` (which will also install the library).

Then you can make a pretty small change to support argon2 hashing.

I tested this by changing just `auth/lib/Encryption.h`, adding:
```
    static string hashArgon2(const string& data);
```

And a trivial implementation in `auth/lib/Encryption.cpp`:
```
#include <sodium.h>

...

string Encryption::hashArgon2(const string& data)
{
    unsigned char buffer[crypto_pwhash_BYTES_MIN] = {0};
    unsigned char salt[crypto_pwhash_argon2id_SALTBYTES];
    for (size_t i = 0; i < crypto_pwhash_argon2id_SALTBYTES; i++) {
        salt[i] = 'A'; // THIS IS A REALLY AWFUL SALT.
    }
    int result = crypto_pwhash(buffer, crypto_pwhash_BYTES_MIN, data.c_str(), data.size(), salt, crypto_pwhash_OPSLIMIT_MIN,
                               crypto_pwhash_MEMLIMIT_MIN, crypto_pwhash_ALG_ARGON2ID13);
    if (result) {
        STHROW("Failed: " + to_string(result));
    }
    return string((char*)buffer, crypto_pwhash_BYTES_MIN);
}
```
(Note: don't use that implementation as-is, it's just there to get it to compile)

Then just two minor Makefile changes:

`auth/Makefile`:
```
-       $(GXX) $(CXXFLAGS) -shared -o $@ $(AUTHOBJ)
+       $(GXX) $(CXXFLAGS) -shared -o $@ $(AUTHOBJ) -lsodium
```

`test/makefile`:
```
-LIBRARIES =-lauth -lbedrock -lstuff -ldl -lpcrecpp -lpthread -lmbedtls -lmbedx509 -lmbedcrypto -lz
+LIBRARIES =-lauth -lbedrock -lstuff -ldl -lpcrecpp -lpthread -lmbedtls -lmbedx509 -lmbedcrypto -lz -lsodium
```

**Comment by joelbettner** [comment]
Sounds good @tylerkaraszewski. There is no need for this PR then.

**Pull request closed without merging**
