### PR TITLE
Increase param size of name in GetJobs

### PR DESCRIPTION
**Pull request by pecanoro**
Do you want me to add a test for this or not really necessary?

## Issue: 

$ https://github.com/Expensify/Expensify/issues/86685

### CODE REVIEW

**Comment by pecanoro** [comment]
I can also create a new constant with a new size, the one that I used seems too big

**Comment by iwiznia** [comment]
> I can also create a new constant with a new size, the one that I used seems too big

It is technically too big, but I am not sure we can know the exact max length to use, right?

**Comment by pecanoro** [comment]
> It is technically too big, but I am not sure we can know the exact max length to use, right?

Huh? I am not following. The current size is the maximum for a SQL query, we can set it to whatever we want between 0 and that size 😄

**Comment by iwiznia** [comment]
lol, I know.. I meant that if 1024*1024 is the max sql query size, can we establish a specific number which will be good for the size of the name? I think not...

**Comment by pecanoro** [comment]
I don't know, the average number of characters for a SSDos job is 40, are we ever going to have more than 100 queues? We could set it to 100*40 for example

**Comment by iwiznia** [comment]
Sounds good to me.

**Comment by pecanoro** [comment]
updated!

**Pull request merged**
