### PR TITLE
Add scan stats to sqlite amalgamation flags

### PR DESCRIPTION
**Pull request by joelbettner**
### Details
@tylerkaraszewski will you please review?

This PR adds `-DSQLITE_ENABLE_STMT_SCANSTATUS=1` to the amalgamation flags for compiling the sqlite binary. We want this because it will allow the SQLite team to better help us make queries more performant.

### Fixed Issues
https://github.com/Expensify/Expensify/issues/260672

### Tests
1. I got the shell.c file from @tylerkaraszewski and added it to the `Bedrock/libstuff` directory (which is where the sqlite3.c file is)
2. From the Bedrock/libstuff folder I ran the following, which created a new sqlite3 binary in the Bedrock/libstuff directory:
```
gcc-9 -DHAVE_READLINE -O2 -Wno-unused-but-set-variable -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_SESSION -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -DSQLITE_ENABLE_NOOP_UPDATE -DSQLITE_MUTEX_ALERT_MILLISECONDS=20 -DHAVE_USLEEP=1 -DSQLITE_MAX_MMAP_SIZE=17592186044416ull -DSQLITE_SHARED_MAPPING -DSQLITE_ENABLE_NORMALIZE -DSQLITE_MAX_PAGE_COUNT=4294967294 -DSQLITE_DISABLE_PAGECACHE_OVERFLOW_STATS -DSQLITE_ENABLE_STMT_SCANSTATUS=1 shell.c sqlite3.c -lpthread -ldl -lm -lreadline -o sqlite3
```
3. I opened an sqlite3 shell with the new binary: 
```
vagrant@expensidev2004:/vagrant/Bedrock/libstuff$ ./sqlite3 -column -header /var/auth/main.db
```
4. I tested the query that we are currently asking the SQLite team to help us with to make sure the scan stats displayed (and that they could be turned off:
```
sqlite> .scanstats on
sqlite> SELECT -(-6000) AS amount, STRFTIME('%s', 'now', 'start of day') AS paymentDate, STRFTIME('%Y-%m-%d %H:%M:%S', 'now', 'start of day') AS readablePaymentDate, '0' AS hasBeenManuallyClearedOfFraud , 'type' AS rnvpName, 'expense' AS reportType UNION ALL SELECT SUM(-r.amount) AS amount, STRFTIME('%s', DATETIME(r.created, 'start of day')) AS paymentDate, STRFTIME('%Y-%m-%d %H:%M:%S', DATETIME(r.created, 'start of day')) AS readablePaymentDate, COALESCE(JSON_EXTRACT(COALESCE(NULLIF(details, ''), '{}'), '$.hasBeenManuallyClearedOfFraud'), JSON('0')) AS hasBeenManuallyClearedOfFraud, rnvp.name AS rnvpName, rnvp.value AS reportType FROM reimbursements r INNER JOIN reportNameValuePairs rnvp ON r.reportID = rnvp.reportID WHERE r.debitBankAccountID IN (583086) AND r.created <= DATETIME('2023-01-16 12:00:00') AND r.created > DATETIME('2023-01-16 12:00:00', 'start of day', '-6 months') AND r.state IN (8, 0, 4, -1, 3, 1) AND r.type NOT IN (5, 8) AND rnvpName = 'type' AND reportType = 'expense' GROUP BY paymentDate, hasBeenManuallyClearedOfFraud ORDER BY paymentDate DESC, hasBeenManuallyClearedOfFraud DESC;
amount  paymentDate  readablePaymentDate  hasBeenManuallyClearedOfFraud  rnvpName  reportType
------  -----------  -------------------  -----------------------------  --------  ----------
6000    1675641600   2023-02-06 00:00:00  0                              type      expense   
-------- scanstats --------
-------- subquery 34 -------
Loop  1: SEARCH r USING INDEX reimbursementsDebitBankAccountIDStateCreated (debitBankAccountID=? AND state=? AND created>? AND created<?)
         nLoop=1        nRow=0        estRow=6        estRow/Loop=6       
-------- subquery 88 -------
Loop  1: SEARCH rnvp USING COVERING INDEX reportNameValuePairsType (reportID=? AND name=? AND value=?)
         nLoop=0        nRow=0        estRow=0        estRow/Loop=1       
---------------------------
sqlite> .scanstats off
sqlite> SELECT -(-6000) AS amount, STRFTIME('%s', 'now', 'start of day') AS paymentDate, STRFTIME('%Y-%m-%d %H:%M:%S', 'now', 'start of day') AS readablePaymentDate, '0' AS hasBeenManuallyClearedOfFraud , 'type' AS rnvpName, 'expense' AS reportType UNION ALL SELECT SUM(-r.amount) AS amount, STRFTIME('%s', DATETIME(r.created, 'start of day')) AS paymentDate, STRFTIME('%Y-%m-%d %H:%M:%S', DATETIME(r.created, 'start of day')) AS readablePaymentDate, COALESCE(JSON_EXTRACT(COALESCE(NULLIF(details, ''), '{}'), '$.hasBeenManuallyClearedOfFraud'), JSON('0')) AS hasBeenManuallyClearedOfFraud, rnvp.name AS rnvpName, rnvp.value AS reportType FROM reimbursements r INNER JOIN reportNameValuePairs rnvp ON r.reportID = rnvp.reportID WHERE r.debitBankAccountID IN (583086) AND r.created <= DATETIME('2023-01-16 12:00:00') AND r.created > DATETIME('2023-01-16 12:00:00', 'start of day', '-6 months') AND r.state IN (8, 0, 4, -1, 3, 1) AND r.type NOT IN (5, 8) AND rnvpName = 'type' AND reportType = 'expense' GROUP BY paymentDate, hasBeenManuallyClearedOfFraud ORDER BY paymentDate DESC, hasBeenManuallyClearedOfFraud DESC;
amount  paymentDate  readablePaymentDate  hasBeenManuallyClearedOfFraud  rnvpName  reportType
------  -----------  -------------------  -----------------------------  --------  ----------
6000    1675641600   2023-02-06 00:00:00  0                              type      expense  
```

### CODE REVIEW

**Review by iwiznia — APPROVED** [review]

**Comment by joelbettner** [comment]
@iwiznia raised a question about this affecting performance [here](https://expensify.slack.com/archives/C094TGUTZ/p1675705794792629?thread_ts=1675704848.904199&cid=C094TGUTZ):

I don't know how to test for that... @tylerkaraszewski @flodnv any ideas?

**Comment by flodnv** [comment]
Let's ask them?

**Review by tylerkaraszewski — CHANGES_REQUESTED** [review]
Why are we adding this to bedrock? The problem in the issue just says to build the shell and run the query.

**Comment by joelbettner** [comment]
@tylerkaraszewski the idea being that with this ability on production, we will be more easily able to do this in the future.

**Comment by tylerkaraszewski** [comment]
If we only need this for the shell and not for bedrock, just add it to the shell build script.

**Comment by tylerkaraszewski** [comment]
I'm also not convinced we'll ever need it again.

**Comment by joelbettner** [comment]
So...is the consensus that in lieu of this PR I should just do something like:
 - copy the `sqlite3.c` file into my home directory on db2.rno
 - upload the `shell.c` file into my home directory on db2.rno
 - Run the following from my home directory on db2.rno to create a sqlite3 binary with the scan stats functionality
```
gcc-9 -DHAVE_READLINE -O2 -Wno-unused-but-set-variable -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_SESSION -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_UPDATE_DELETE_LIMIT -DSQLITE_ENABLE_NOOP_UPDATE -DSQLITE_MUTEX_ALERT_MILLISECONDS=20 -DHAVE_USLEEP=1 -DSQLITE_MAX_MMAP_SIZE=17592186044416ull -DSQLITE_SHARED_MAPPING -DSQLITE_ENABLE_NORMALIZE -DSQLITE_MAX_PAGE_COUNT=4294967294 -DSQLITE_DISABLE_PAGECACHE_OVERFLOW_STATS -DSQLITE_ENABLE_STMT_SCANSTATUS=1 shell.c sqlite3.c -lpthread -ldl -lm -lreadline -o sqlite3
```
 - Use the new binary in my home directory on db2.rno to open a sqlite3 shell that queries the production database
 ```
./sqlite3 -column -header /var/lib/authdb/main.db
 ```
 - Enable the scanstats functionality and run the slow query
 ```
 sqlite> .scanstats on
sqlite> SELECT -(-6000) AS amount, STRFTIME('%s', 'now', 'start of day') AS paymentDate, STRFTIME('%Y-%m-%d %H:%M:%S', 'now', 'start of day') AS readablePaymentDate, '0' AS hasBeenManuallyClearedOfFraud , 'type' AS rnvpName, 'expense' AS reportType UNION ALL SELECT SUM(-r.amount) AS amount, STRFTIME('%s', DATETIME(r.created, 'start of day')) AS paymentDate, STRFTIME('%Y-%m-%d %H:%M:%S', DATETIME(r.created, 'start of day')) AS readablePaymentDate, COALESCE(JSON_EXTRACT(COALESCE(NULLIF(details, ''), '{}'), '$.hasBeenManuallyClearedOfFraud'), JSON('0')) AS hasBeenManuallyClearedOfFraud, rnvp.name AS rnvpName, rnvp.value AS reportType FROM reimbursements r INNER JOIN reportNameValuePairs rnvp ON r.reportID = rnvp.reportID WHERE r.debitBankAccountID IN (583086) AND r.created <= DATETIME('2023-01-16 12:00:00') AND r.created > DATETIME('2023-01-16 12:00:00', 'start of day', '-6 months') AND r.state IN (8, 0, 4, -1, 3, 1) AND r.type NOT IN (5, 8) AND rnvpName = 'type' AND reportType = 'expense' GROUP BY paymentDate, hasBeenManuallyClearedOfFraud ORDER BY paymentDate DESC, hasBeenManuallyClearedOfFraud DESC;
```

**Pull request closed without merging**
