### PR TITLE
[HOLD] Upgrade mbedtls to 3.5.2

### PR DESCRIPTION
**Pull request by johnmlee101**
Turns out 3.6.0 doesn't work with TLS v1.3 

Was trying to figure this out for awhile and got errors like https://github.com/Mbed-TLS/mbedtls/issues/9223

and internal errors, but once I downgraded to 3.5.2 it worked instantly. 

The rest is optimizations and improvements to move to 3.0+ but we'll still need to upgrade at some point to a higher version once they fix the issues.

### CODE REVIEW

**Review by Julesssss — COMMENTED** [review]
I'm not following all of these changes, are the private SSL changes necessary for the newer version of mbedtls?

**Comment by johnmlee101** [comment]
Will need to make sure Auth and the other plugins work with this as well, which is why its on hold before we merge

**Comment by johnmlee101** [comment]
>  are the private SSL changes necessary for the newer version of mbedtls?

Yeah they explicitly make sure its accessed internally or externally with private_ prefixes now

**Comment by johnmlee101** [comment]
Auth: https://github.com/Expensify/Auth/pull/11565

**Comment by johnmlee101** [comment]
Okay Fuzzybot, ExpensifyTableManager, ExpensifyBackupManager all compile and run with the updated version, so we'll want to merge this first, merge auth, then deploy asap so that auth using the bedrock prod branch doesn't break things

**Review by tylerkaraszewski — APPROVED** [review]

**Comment by tylerkaraszewski** [comment]
Approved this, but letting you figure out the required deploy dance.

**Comment by johnmlee101** [comment]
Oh do you mind approving https://github.com/Expensify/Auth/pull/11565 as well then?

**Comment by tylerkaraszewski** [comment]
Done.

**Review by Julesssss — APPROVED** [review]

**Comment by Julesssss** [comment]
Is this still held @johnmlee101?

**Comment by johnmlee101** [comment]
yes, since this will require a specific deployment order to prevent auth from crashing in tests

**Comment by johnmlee101** [comment]
I'm going to be OOO, and I don't think this is too time-sensitive, so I might resume this once I'm back, and since its also Friday I don't want to force a deploy today.

**Comment by tylerkaraszewski** [comment]
I think this has been abandoned. Should we close or update this PR?

**Pull request closed without merging**
