### PR TITLE
Changed protocol to 4.1 from 3.2 including column definitions

### PR DESCRIPTION
**Pull request by divaykin**
In order to support MySQL 5.6, MySQL 5.7 and MariaDB 15 we have to upgrade protocol from 3.2 to 4.1 version. Seems like recent versions of MySQL clients do not support old 3.2 protocol.

This includes changing ColumnDefinition packet according to https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-COM_QUERY_Response

After the patch:
```
denis@u16:~$ mysql --version && mysql -h127.0.0.1 -e "SELECT 1 AS foo, 2 AS bar;"
mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
+------+------+
| foo  | bar  |
+------+------+
|    1 |    2 |
+------+------+
```
```
denis@u16:~$ mysql --version && mysql -h127.0.0.1 -e "SELECT 1 AS foo, 2 AS bar;"
mysql  Ver 14.14 Distrib 5.6.16, for debian-linux-gnu (x86_64) using  EditLine wrapper
+------+------+
| foo  | bar  |
+------+------+
|    1 |    2 |
+------+------+
```
```
denis@u16:~$ mysql --version && mysql -h127.0.0.1 -e "SELECT 1 AS foo, 2 AS bar;"
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
+------+------+
| foo  | bar  |
+------+------+
|    1 |    2 |
+------+------+
```

### CODE REVIEW

**Comment by divaykin** [comment]
See also https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-Protocol::ColumnDefinition41 for some details of changes in column definitions

**Comment by tylerkaraszewski** [comment]
This still doesn't work for me. Building bedrock on this branch gives me the following when sending it a `Status` message:

```
Status

200 OK
commitCount: 389
nodeName: bedrock
processingTime: 0
totalTime: 0
waitTime: 0
Content-Length: 377

{"commitCount":389,"escalatedCommandList":[],"hash":"D729C5DEC6F6373D64678EDA077357355F0D5CB0","isMaster":true,"peerList":[],"plugins":[{"name":"DB"},{"name":"Status"},{"name":"Jobs"},{"name":"Cache"},{"name":"MySQL"},{"name":"Concierge"}],"priority":200,"processedCommandList":[],"queuedCommandList":[],"state":"MASTERING","version":"47fa47ff0605e9167d79d6ab5042d3ea6d1c3424"}
```

Which seems to indicate the correct version `47fa47ff0605e9167d79d6ab5042d3ea6d1c3424`.

However, when I try to connect to it, I get the same error:

```
> mysql --version && mysql -h127.0.0.1 -e "SELECT 1 AS foo, 2 AS bar;"
mysql  Ver 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64) using  EditLine wrapper
ERROR 2012 (HY000): Error in server handshake
```

It would be nice if we could get a little better description of the best way to test and/or diagnose problems here.

**Comment by divaykin** [comment]
@tylerkaraszewski it's strange. tried newer (5.6.35) mysql:
```
denis@u16:~/dev/bedrock/Bedrock$ mysql --version && mysql -h127.0.0.1 -e "SELECT 1 AS foo, 2 AS bar; select @@version_comment;"
mysql  Ver 14.14 Distrib 5.6.35, for debian-linux-gnu (x86_64) using  EditLine wrapper
+------+------+
| foo  | bar  |
+------+------+
|    1 |    2 |
+------+------+
+------------------------------------------+
| version_comment                          |
+------------------------------------------+
| 47fa47ff0605e9167d79d6ab5042d3ea6d1c3424 |
+------------------------------------------+
```
Have the following checksums and compiler versions:
```
denis@u16:~/dev/bedrock/Bedrock$ md5sum bedrock 
42112f53e97953aa0680e53959e9df24  bedrock
denis@u16:~/dev/bedrock/Bedrock$ g++-6 --version
g++-6 (Ubuntu 6.2.0-3ubuntu11~16.04) 6.2.0 20160901
```

Basically network protocol is wrong which might be diagnosed from tcpdump analysis i.e. would be great to have dump of the following command: `sudo tcpdump -vX -i lo`. Also any chance I can get ssh to the box where the problem is reproducible?

@quinthar sounds like it's a bit involving as I can't reproduce an issue locally anymore. Would you mind getting back to me on upwork.com? Thx

**Comment by tylerkaraszewski** [comment]
tcpdump output:
```
18:06:20.067141 IP (tos 0x0, ttl 64, id 57053, offset 0, flags [DF], proto TCP (6), length 60)
    localhost.49235 > localhost.mysql: Flags [S], cksum 0xfe30 (incorrect -> 0x7c14), seq 2016805097, win 43690, options [mss 65495,sackOK,TS val 76144180 ecr 0,nop,wscale 7], length 0
	0x0000:  4500 003c dedd 4000 4006 5ddc 7f00 0001  E..<..@.@.].....
	0x0010:  7f00 0001 c053 0cea 7836 00e9 0000 0000  .....S..x6......
	0x0020:  a002 aaaa fe30 0000 0204 ffd7 0402 080a  .....0..........
	0x0030:  0489 de34 0000 0000 0103 0307            ...4........
18:06:20.067152 IP (tos 0x0, ttl 64, id 1478, offset 0, flags [DF], proto TCP (6), length 40)
    localhost.mysql > localhost.49235: Flags [R.], cksum 0x6b70 (correct), seq 0, ack 2016805098, win 0, length 0
	0x0000:  4500 0028 05c6 4000 4006 3708 7f00 0001  E..(..@.@.7.....
	0x0010:  7f00 0001 0cea c053 0000 0000 7836 00ea  .......S....x6..
	0x0020:  5014 0000 6b70 0000                      P...kp..
^C
14 packets captured
28 packets received by filter
0 packets dropped by kernel
```

Command run:
```
$ mysql --version && mysql -h127.0.0.1 -e "SELECT 1 AS foo, 2 AS bar; select @@version_comment;"
mysql  Ver 14.14 Distrib 5.6.33, for debian-linux-gnu (x86_64) using  EditLine wrapper
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
```

md5:
```
$ md5sum bedrock
549d39d5d68f81936c56b6018bd472d7  bedrock
```

g++ version:
```
$ g++-6 --version
g++-6 (Ubuntu 6.2.0-3ubuntu11~14.04) 6.2.0 20160901
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by quinthar** [comment]
Per our discussion on Upwork, please keep grinding on this one.  Let's get
it working reliably for a broad range of versions.  Thanks!

**Comment by divaykin** [comment]
@tylerkaraszewski according to above you just can't connect at all (i.e. different error)
`Can't connect to MySQL server on '127.0.0.1' (111)` vs earlier `ERROR 2012 (HY000): Error in server handshake`.

I'm suspecting your MySQL plugin .cpp file has not been recompiled.

I need access to the system (ssh) where I can reproduce this to move any further.

**Comment by divaykin** [comment]
Hi @tylerkaraszewski may I ask you to help me accessing any host where I can reproduce what you're seeing please? Please contact me at denis.ivaykin@gmail.com with connection details. Thanks!

**Comment by tylerkaraszewski** [comment]
@divaykin Yes, the problem is that the place where I'm seeing this is a company-owned laptop that I can't give you access to. I'll try and reproduce the problem on another machine.

**Comment by tylerkaraszewski** [comment]
I was trying to come up with steps to create a reproducible environment for this, but not it's working for me, so I'm going to see if I can get it to work in my test environment as well. I'll get back to you here after I try that.

**Pull request merged**
