### PR TITLE
Add transaction times

### PR DESCRIPTION
**Pull request by aldo-expensify**
### Details

Add times in [BedrockServer](https://github.com/Expensify/Bedrock/blob/293242bbbbb25bdf1fa55e6f6147aa363ca69bfe/BedrockServer.cpp#L973-L978) based on what we already had in [SQLiteNode](https://github.com/Expensify/Bedrock/blob/293242bbbbb25bdf1fa55e6f6147aa363ca69bfe/sqlitecluster/SQLiteNode.cpp#L952-L959)

Non-blocking example:

```
2023-05-02T23:42:17.144702+00:00 expensidev2004 bedrock: xxxxxx (SQLiteNode.cpp:952) update [sync] [info] {auth/LEADING} Committed leader transaction for '3420652 (9D0D472EBA5A0DAC84C8AC3F3B05D21D8372940B).  (consistencyRequired=QUORUM), 0 of 0 approved (0 total) in 401 ms (0+396+1+0+3+0ms)
2023-05-02T23:42:17.504326+00:00 expensidev2004 bedrock: umiM0Y admin@many-reports.com (BedrockServer.cpp:973) runCommand [socket1] [info] Committed leader transaction #3420653(E9780296CD3710C97216FCF59D38931B2FD52E70). Command: 'SetNameValuePairs', blocking: false in 3 ms (0+0+0+0+2+0ms)
2023-05-02T23:42:17.554035+00:00 expensidev2004 bedrock: xxxxxx (SQLiteNode.cpp:952) update [sync] [info] {bedrock/LEADING} Committed leader transaction for '666737 (2FD1284F1A7EC7E9133CF0D83A11D7D6286744FA).  (consistencyRequired=QUORUM), 0 of 0 approved (0 total) in 1 ms (0+0+0+0+1+0ms)
2023-05-02T23:42:23.601750+00:00 expensidev2004 bedrock: xxxxxx (SQLiteNode.cpp:952) update [sync] [info] {auth/LEADING} Committed leader transaction for '3420654 (0C42D2A23280CC485B6592FA409DA2840321BF64).  (consistencyRequired=QUORUM), 0 of 0 approved (0 total) in 396 ms (0+393+0+0+2+0ms)
2023-05-02T23:42:29.231292+00:00 expensidev2004 bedrock: DTN55I admin@many-reports.com (BedrockServer.cpp:973) runCommand [socket2] [info] Committed leader transaction #3420655(488463D48797A782980E0B863BD278314C69A45E). Command: 'UpdateRNVPLastReadTime', blocking: false in 1 ms (0+0+0+0+1+0ms)
2023-05-02T23:42:41.207475+00:00 expensidev2004 bedrock: XtwiPw 500000reports@many-reports.com (BedrockServer.cpp:973) runCommand [socket23] [info] Committed leader transaction #3420656(46EAD56FF6403C3D60E11D5BFC6FA37E0F716EBC). Command: 'CreateAccount', blocking: false in 13 ms (0+3+6+0+2+0ms)
2023-05-02T23:42:41.237261+00:00 expensidev2004 bedrock: XtwiPw 500000reports@many-reports.com (BedrockServer.cpp:969) runCommand [socket824] [info] Committed leader transaction #666738(D66660EF1F6AFF1BD7BCCCEC85EF9829CA3654BC). Command: 'CreateJob', blocking: false
2023-05-02T23:42:53.887188+00:00 expensidev2004 bedrock: XtwiPw 500000reports@many-reports.com (BedrockServer.cpp:973) runCommand [socket23] [info] Committed leader transaction #3420657(10E9D6DF92730C9F8D9F9F4369B7F3568DE2B869). Command: 'SharePolicy', blocking: false in 11217 ms (0+9741+730+33+712+0ms)
```

Blocking queue example:

```
2023-05-03T00:13:08.187462+00:00 expensidev2004 bedrock: cxGedN 102@expensifail.com (BedrockServer.cpp:973) runCommand [blockingCommit] [info] Committed leader transaction #3421427(0C0FFC98ADC007EF26EECB4B7E140B95F5B801F9). Command: 'SharePolicy', blocking: true, in 10 ms (0+4+1+0+3+0ms)
2023-05-03T00:13:08.199383+00:00 expensidev2004 bedrock: YLx7R5 102@expensifail.com (BedrockServer.cpp:973) runCommand [blockingCommit] [info] Committed leader transaction #3421429(3D83D31B71167E269230A75F1DC9FCCD94AFE46E). Command: 'SharePolicy', blocking: true, in 5 ms (0+3+0+0+0+0ms)
2023-05-03T00:13:08.209648+00:00 expensidev2004 bedrock: Uov8WV 102@expensifail.com (BedrockServer.cpp:973) runCommand [blockingCommit] [info] Committed leader transaction #3421430(47ABA6F4D2C23DFFF41FAADB9B2788A89F009E86). Command: 'SharePolicy', blocking: true, in 5 ms (0+3+0+0+0+0ms)
2023-05-03T00:13:08.223188+00:00 expensidev2004 bedrock: 4SxLx4 102@expensifail.com (BedrockServer.cpp:973) runCommand [blockingCommit] [info] Committed leader transaction #3421431(51729CFFDB3C8D42F05C914EF2FBC7DA11159FEE). Command: 'SharePolicy', blocking: true, in 8 ms (0+5+1+0+0+0ms)
```

### Fixed Issues
Part of https://github.com/Expensify/Expensify/issues/280378#issue-1693089101 

### Tests

Watch for `Committed leader transaction` in the logs. Found lines should include times.
_________
**Internal Testing Reminder:** when changing bedrock, please compile auth against your new changes

### CODE REVIEW

**Comment by aldo-expensify** [comment]
cc @tylerkaraszewski does this make sense to you? We are trying to log the time a transaction (command) spent in blocking queue.

**Comment by tylerkaraszewski** [comment]
We already record queue time here:
https://github.com/Expensify/Bedrock/blob/6c467d1deca642e5f8ea554dfe61b27633989e23/BedrockCommand.cpp#L138

We have `QUEUE_WORKER` and `QUEUE_SYNC` but don't currently have `QUEUE_BLOCKING`, which is likely what we should add.

These are used here:
https://github.com/Expensify/Bedrock/blob/6c467d1deca642e5f8ea554dfe61b27633989e23/BedrockCommandQueue.cpp#L3-L13

We dhould sub-class `BedrockCommandQueue` with `BedrockBlockingCommandQueue` and override those to use `QUEUE_BLOCKING`

Then we can update the type of queue here:
https://github.com/Expensify/Bedrock/blob/6c467d1deca642e5f8ea554dfe61b27633989e23/BedrockServer.h#L263

**Comment by aldo-expensify** [comment]
Thanks @tylerkaraszewski for all the info.. I'll have a look tomorrow

**Comment by aldo-expensify** [comment]
Closing in favor of https://github.com/Expensify/Bedrock/pull/1502

**Pull request closed without merging**
