### PR TITLE
Return all jobs if mockRequest set as true

### PR DESCRIPTION
**Pull request by mattabullock**
We want to return all jobs when adding the mockRequest header so we can automatically mark mocked jobs as completed.

Related to: https://github.com/Expensify/Expensify/issues/75752

# Tests
Test with this PR: https://github.com/Expensify/Bedrock-PHP/pull/86
1. Create job with mockRequest header
2. Run BWM
3. Make sure the job is marked as finished and then deleted but does not run.

### CODE REVIEW

**Comment by mattabullock** [comment]
Bump

**Comment by tylerkaraszewski** [comment]
Shouldn't the [HOLD] on the Bedrock-PHP change be on this change instead, and we should merge this change after that one?

**Comment by mattabullock** [comment]
No I believe because if we start sending mockrequest early, it's going to only pull mocked jobs and not the real ones.

**Comment by tylerkaraszewski** [comment]
Approved (sorry that was late), has conflicts now, though.

**Comment by mattabullock** [comment]
conflicts should be fixed

**Comment by mattabullock** [comment]
updated

**Pull request merged**
