### PR TITLE
More exception details

### PR DESCRIPTION
**Pull request by tylerkaraszewski**
### Details
Adds extra info documenting exception origin to errors, gated behind a command-line flag that's only enabled in tests.

### Fixed Issues
Fixeshttps://github.com/Expensify/Expensify/issues/264120

### Tests

I tested this by breaking a test on purpose:
```
--- a/test/tests/ReadTest.cpp
+++ b/test/tests/ReadTest.cpp
@@ -22,7 +22,7 @@ struct ReadTest : tpunit::TestFixture {

     void simpleRead() {
         SData status("Query");
-        status["query"] = "SELECT 1;";
+        status["query"] = "ELECT 1;";
         string response = tester->executeWaitVerifyContent(status);
         int val = SToInt(response);
         ASSERT_EQUAL(val, 1);
```

And verifying it failed with extra data shown:
```
vagrant@expensidev2004:/vagrant/Bedrock/test$ ./test -only Read
--------------
   exception #1 from ReadTest::simpleRead with cause: Expected 200 OK, but got '402 Bad query'. Initially thrown from: DB.cpp:67
❌ !FAILED! ❌ ReadTest::simpleRead
```

_________
**Internal Testing Reminder:** when changing bedrock, please compile auth against your new changes

### CODE REVIEW

**Comment by johnmlee101** [comment]
Hmm, so in our tests if an ASSERT fails, we bubble it up like 
```
(Integral): 0 != 3000000
   assertion #1 at testpath/test.cpp:418
```

How hard is it for us to have exceptions look like
```
exception #1 from Test::test with cause: Expected 404, but got '200' at testpath/test.cpp:418.
```

Since the issue I'm having is if I have 20 tester->executeWaits, I have 0 clue which one failed with that error.

**Comment by johnmlee101** [comment]
> We might need to print the whole callstack.

I think that's fine as well. I don't think it should cloud the tests with too much information, as long as it helps with the debugging process!

**Comment by tylerkaraszewski** [comment]
I don't think this is going to work the way you want it to, @johnmlee101.

**Comment by tylerkaraszewski** [comment]
The callstack doesn't have line numbers, so if you write code that does:

```
int myFunc() {
    tester->executeWaitVerifyContent(A);
    tester->executeWaitVerifyContent(A);
    tester->executeWaitVerifyContent(A);
    tester->executeWaitVerifyContent(A);
}
```

The callstack doesn't have line numbers, it just says you're in `executeWaitVerifyContent` inside `myFunc` in every case.

**Comment by johnmlee101** [comment]
Damn, suppose this is another reason to get C++20 
https://en.cppreference.com/w/cpp/utility/source_location
😅

**Comment by tylerkaraszewski** [comment]
https://en.cppreference.com/w/cpp/header/stacktrace will probably give us exactly what we want. Looks like we need at least g++ 12.1

**Review by johnmlee101 — APPROVED** [review]
I think we can follow-up with upgrading C++ if we want, but this is a good start

**Pull request merged**
