### PR TITLE
Bring back nodeName to the response

### PR DESCRIPTION
**Pull request by flodnv**
@tylerkaraszewski please review -- not sure if this is the most appropriate spot.

Needed for https://github.com/Expensify/Expensify/issues/57120

### CODE REVIEW

**Comment by flodnv** [comment]
Updated and retested @tylerkaraszewski, thanks!

**Comment by tylerkaraszewski** [comment]
I'd merge, but Travis seems broken. I'll wait and try again.

**Comment by tylerkaraszewski** [comment]
@flodnv - Travis is being weird. Want to try pushing another commit or something to get it to work?

**Comment by flodnv** [comment]
@tylerkaraszewski updated with a force push 😁

**Comment by botify** [comment]
Deployed to Bedrock () by florent

**Pull request merged**
