### PR TITLE
Revert second attempt at retryAfter

### PR DESCRIPTION
**Pull request by mea36**
Reverts https://github.com/Expensify/Bedrock/pull/243

Fixes
$ https://github.com/Expensify/Expensify/issues/61957

I did this by hand.  I reverted all of Jobs.cpp except the addition of `_isValidSQLiteDateModifier`
I left in any tests that were added in #243 but had nothing to do with `retryAfter` or `REQUEUED`

### CODE REVIEW

**Comment by mea36** [comment]
Ya, I'm ok with holding off on merging this until we've had the opportunity to investigate.

**Comment by cead22** [comment]
So what's the game plan?

**Comment by mea36** [comment]
https://github.com/Expensify/Expensify/issues/61957#issuecomment-329602084

**Comment by mea36** [comment]
Closing in favor of https://github.com/Expensify/Bedrock/pull/285

**Pull request closed without merging**
