### PR TITLE
Revert old performance change

### PR DESCRIPTION
**Pull request by tylerkaraszewski**
This removes an old change where we'd close the command port while upgrading to avoid escalating tons of read commands to the leader from followers (because they're on the wrong version). Leader should now be capable of handling this extra read traffic during upgrades, and this hopefully resolves issues where clients can't connect to servers that are expected to be up, occasionally even running out of connection retries.

Addresses this issue:
$ https://github.com/Expensify/Expensify/issues/104706

The original change for this dates back at least as long as Bedrock has been open source, which can be seen here:

https://github.com/Expensify/Bedrock/blob/ea1aeca6a85f4957a3098f6eed742435eca19f89/BedrockServer.cpp#L432-L439

No tests were added for this, only existing tests run.

### CODE REVIEW

**Comment by quinthar** [comment]
While making changes to Bedrock, can you attempt to refactor references to "slave" to "follower", and "master" to "leader"?

**Comment by tylerkaraszewski** [comment]
> While making changes to Bedrock, can you attempt to refactor references to "slave" to "follower", and "master" to "leader"?

I caught myself writing the description and did this before posting. The actual change is just a deletion, and the code deleted had already been refactored to use leader/follower. Are you referring to the code referenced indicating where this was initially added?

**Comment by quinthar** [comment]
Oh, I just mean we should clean up that language as we go, and I noticed in your code snippet.  Anyway, sounds like we agree.

**Comment by tylerkaraszewski** [comment]
I think all references to master/slave are already removed except where they are still required for backwards-compatibility. The challenge for me has been remembering to use the new rather than old terminology.

**Comment by tylerkaraszewski** [comment]
We're undoing the change above because it turns out it allows us to run `peek` for two different versions of the code at the same time, which is bad. We'll have to come up with a better solution than that one for this.

**Pull request merged**
