### PR TITLE
Switch to c++17 to get new mutex types and other new features

### PR DESCRIPTION
**Pull request by coleaeason**
@tylerkaraszewski Please review. Switches us to c++17 std, which gives us `shared_mutex`, some new string functions like `starts_with()` and `ends_with()` and more.

## Tests
Compiles, tests run 🤷‍♂️

### CODE REVIEW

**Comment by tylerkaraszewski** [comment]
I think we'll need to do this in all of our other repos as well.

**Comment by quinthar** [comment]
What new mutex type does this open up that we care about?

**Comment by coleaeason** [comment]
>What new mutex type does this open up that we care about?

It gives us `shared_mutex` as opposed to having to use `shared_timed_mutex` which has features we don't use. It also gives us new string functions that we could use from the standard library instead of our own. 

>I think we'll need to do this in all of our other repos as well.

Yeah, I have those PRs coming too.

**Comment by tylerkaraszewski** [comment]
C++17 also adds [std::filesystem](https://en.cppreference.com/w/cpp/filesystem), some parallel algorithms that might be useful (though I don't have a current use case for them).

**Review by tylerkaraszewski — APPROVED** [review]

**Pull request merged**
